plugins {
    id "com.android.application"
}

android {
    namespace "ru.slavitsa.sverkapro"
    compileSdk 34

    defaultConfig {
        applicationId "ru.slavitsa.sverkapro"
        minSdk 23
        targetSdk 34
        versionCode 20002
        versionName "2.0.2"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }

    packaging {
        resources.excludes += ["META-INF/DEPENDENCIES", "META-INF/LICENSE*", "META-INF/NOTICE*"]
    }
}

dependencies {
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.1.4"
    implementation("net.sourceforge.jexcelapi:jxl:2.6.12") {
        exclude group: "log4j", module: "log4j"
    }
}
